wip

diff --git a/pgvm_create b/pgvm_create
--- a/pgvm_create
+++ b/pgvm_create
@@ -11,11 +11,7 @@
 # désactive l'interprétation de '!' dans une chaine
 set +H
 
-
 YEARDAY=$(date '+%y%j')
-#echo $YEARDAY
-#exit
-
 
 ISOK=$(zenity --question --text "L'inventaire des machines est-il à jour?")
 if [ $? != 0 ]; then
@@ -56,7 +52,6 @@ if [ $? != 0 ]; then
 fi
 echo "TEMPLATE=$TEMPLATE"
 
-
 # récupération du vmid du template
 IFS=";";while read -a ARR
 do
@@ -74,7 +69,16 @@ if [ $? != 0 ]; then
 	echo "Interruption"; exit 1
 fi
 
-echo "NB=$NB"
+#echo "NB=$NB"
+i=$NB
+((i++))
+((i--))
+if ! [ "$i" = "$NB" ];
+then
+	zenity --error --text "invalid value '$NB'"
+#	echo "Erreur: valeur '$NB' invalide"
+	exit 1
+fi
 
 
 MOD=$(zenity --entry --text "Donner le nom du module (RXXX, SAETTT)\n(servira pour le nom des VM)")
@@ -113,29 +117,31 @@ echo "START=$START"
 
 #-------------------------
 # Creation des clones
-#set -x
+IFS=$'\n'
 for i in $(seq 1 $NB)
 do
 	NUM=$i
-	if [ 1 = ${#i} ]; then NUM=0$i;fi
-	echo "NUM=$NUM, size=${#NUM}"
+	if [ 1 = ${#i} ]; then NUM="0$i";fi
+	echo "i=-$i- NUM=-$NUM-, size=${#NUM}"
 	echo "CREATION CLONE i=$NUM, nom=${MOD}_$i, id=${YEARDAY}${ID}${NUM}"
 
 # ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/clone
 	response=$(curl -k \
 		--silent -X POST \
-		-H "Authorization: PVEAPIToken=${USER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-		"https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$NODE/qemu/$VMID/clone?node=$NODE&vmid=$VMID&newid=${YEARDAY}${ID}${NUM}&name=${MOD}_$i")
+		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+		"https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$NODE/qemu/$VMID/clone?node=$NODE&vmid=$VMID&newid=${YEARDAY}${ID}${NUM}&name=${MOD}-$i")
 	err=$?
 	echo "response=-$response- err=$err"
 	if ! [ $err = 0 ]; then exit 1; fi
+done
 
+exit 0
 
 	echo "Ajout des tags"
 # ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/config
 	response=$(curl -k \
 		--silent -X POST \
-		-H "Authorization: PVEAPIToken=${USER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
 		"https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$NODE/qemu/$VMID/config?node=$NODE&vmid=$VMID&tags=$TAGS")
 	err=$?
 	echo "response=$response err=$err"
@@ -143,3 +149,4 @@ do
 
 done
 
+exit 0
