suppression creation par num, ajout description clone

diff --git a/pgvm b/pgvm
--- a/pgvm
+++ b/pgvm
@@ -65,6 +65,7 @@ function ApiCall()
 }
 
 
+
 #================================================================
 # Fetch data of a given node ($1), called by FetchData()
 function ProcessNode()
@@ -125,20 +126,11 @@ function FetchData()
 # clean out old data
 	rm /tmp/proxmox/tags.csv 2>/dev/null
 	rm data_* 2>/dev/null
+	TAGAARR=()
 	
 # Fetch list of nodes
 	ApiCall GET "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes"
-#	curl --silent -k \
-#		-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-#		https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes|jq | jq -r '.data[] | .node' >data_nodes.csv 2>>$CURLLOG
-	
 	jq  -r '.data[] | .node' <<<"$response" >data_nodes.csv 2>>$CURLLOG
-#	err=$?
-#	if ! [ $err = 0 ];
-#	then
-#		echo "Error: API call failure, err=$?"
-#		exit 1
-#	fi
 
 # Main API loop, iterate on all nodes and collect all the nodes data
 	while read -r NODE
@@ -180,16 +172,7 @@ function FetchData()
 
 # Generate a csv file for each group, holding the users
 	ApiCall GET "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/users?full=1"
-#	curl --insecure --silent -X GET \
-#		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-#		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/users?full=1" | jq '.data[]' >/tmp/proxmox/users.json
 	jq -r '.data[]' <<<$response >/tmp/proxmox/users.json
-
-	err=$?
-	if [ $err != 0 ]; then
-		echo "Error: failure of operation, err=$err";
-		exit 1
-	fi
 
 # convert json into 3-fields CSV file
 	jq -r '.userid + ";" + .groups + ";" + .email'</tmp/proxmox/users.json >/tmp/proxmox/users.csv
@@ -263,11 +246,14 @@ function ShowTags()
 {
 	COMPT=0
 	printf "\n|   %2d Tags  | #VM+T. |\n|------------+--------|\n" $(wc -l <data_tags.csv)
-	NUM=1
 	while read TAG
 	do
-		printf "| %10s | %6d |\n" $TAG ${TAGAARR[$TAG]}
-		((COMPT+=${TAGAARR[$i]}))
+		if [ "$TAG" = " " ]; then
+			printf "| (sans tag) | %6d |\n" ${TAGAARR[$TAG]}
+		else
+			printf "| %10s | %6d |\n" $TAG ${TAGAARR[$TAG]}
+		fi
+		((COMPT+=${TAGAARR[$TAG]}))
 	done <data_tags.csv
 	echo "|------------+--------|"
 	printf "       Total | %6d |\n" $COMPT
@@ -361,15 +347,16 @@ do
 					echo "node ${TAB[0]}: machine ${TAB[2]}, id=${TAB[1]} est un template, pas de suppression"
 				else
 					echo "node ${TAB[0]}: suppression machine ${TAB[2]}, id=${TAB[1]}"
-					response=$(curl --insecure --silent -X DELETE \
-						-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-						"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/${TAB[0]}/qemu/${TAB[1]}?node=${TAB[0]}&vmid=${TAB[1]}")
-					err=$?
+					ApiCall DELETE "https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/${TAB[0]}/qemu/${TAB[1]}?node=${TAB[0]}&vmid=${TAB[1]}"
+#					response=$(curl --insecure --silent -X DELETE \
+#						-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+#						"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/${TAB[0]}/qemu/${TAB[1]}?node=${TAB[0]}&vmid=${TAB[1]}")
+#					err=$?
 
-					if [ $err != 0 ]; then
-						echo "Error: failure of delete operation, err=$err, response='$response'";
-						exit 1
-					fi
+#					if [ $err != 0 ]; then
+#						echo "Error: failure of delete operation, err=$err, response='$response'";
+#						exit 1
+#					fi
 					((COMPT++))
 				fi
 			fi
@@ -540,6 +527,7 @@ ToolCheck zenity
 VarCheck $TOK_VALUE TOK_VALUE
 VarCheck $TOK_NAME TOK_NAME
 VarCheck $REALM REALM
+VarCheck $PVUSER PVUSER
 VarCheck $APINODE APINODE
 VarCheck $DOMAIN DOMAIN
 VarCheck $PORT PORT
@@ -567,7 +555,7 @@ items=("Affichage Dashboard" \
 	"Liste VMs par node" \
 	"Liste VMs par tag" \
 	"Création VMs" \
-	"Suppression VMs" \
+	"Suppression VMs par tag" \
 	"Liste des users par groupe")
 
 while item=$(zenity --height=400 --width=300 --list \
@@ -580,7 +568,7 @@ do
 	fi
 
 	case "$item" in
-		"${items[0]}") ShowDashboard;;
+		"${items[0]}") FetchData; ShowDashboard;;
 		"${items[1]}") ViewVmByNode;;
 		"${items[2]}") ViewVmByTag;;
 		"${items[3]}") ./pgvm_create; FetchData; ShowDashboard;;
diff --git a/pgvm_create b/pgvm_create
--- a/pgvm_create
+++ b/pgvm_create
@@ -10,20 +10,26 @@
 set +H
 
 YEARDAY=$(date '+%y%j')
+TODAY=$(date '+%Y%m%d_%H%M%S')
 
 #================================================================
 function CreateClone()
 {
-
 	if [ "$DEBUG" = "Y" ]; then
 		echo "-Creation clone sur le node $BASENODE (Id=$TVMID): nom=${VMNAME}, id=$VMID"
 	fi
-
+	DESC="VM Cloned from template $TEMPLATE (Id=$TVMID), created on $TODAY by user $PVUSER"
+	
 # ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/clone
 	response=$(curl -k \
 		--silent -X POST \
 		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$TVMID/clone?node=$BASENODE&vmid=$TVMID&newid=$VMID&name=${VMNAME}")
+		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$TVMID/clone?node=$BASENODE&vmid=$TVMID&newid=$VMID&name=${VMNAME}" \
+		--data-urlencode node=$BASENODE \
+		--data-urlencode vmid=$TVMID \
+		--data-urlencode newid=$VMID \
+		--data-urlencode name=$VMNAME \
+		--data-urlencode description="$DESC")
 	err=$?
 	if ! [ $err = 0 ]; then
 		echo "response=-$response- err=$err"; exit 1
@@ -140,17 +146,7 @@ do
 	fi
 done
 
-# How are the machine named ?
-NAMING=$(zenity --list --text "Type de nommage?" --column="Type" Numérotation Utilisateur )
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
-NAMETYPE=NTN
-if [ "$NAMING" = "Utilisateur" ]; then
-	NAMETYPE=NTU
-fi
 
-#echo "NAMING=$NAMING NAMETYPE=$NAMETYPE" 
 
 # create an array holding the group names, just for the zenity call below
 unset GROUPARR
@@ -161,34 +157,13 @@ do
 done < data_groups.csv
 echo "GROUPARR=${GROUPARR[@]}"
 
-if [ "$NAMETYPE" = "NTU" ]
-then
-	GROUPSEL=$(zenity --list --text "Quel groupe d'utilisateurs?" --column="Groupe" ${GROUPARR[@]} )
-	if [ $? != 0 ]; then
-		echo "Interruption"; exit 1
-	fi
-	echo "GROUPSEL=$GROUPSEL"
-	VMNAMES="${MOD}-XXX (avec XXX l'id user)"
-	NB=$(wc -l <data_group_${GROUPSEL}.csv)
-#	
-else
-	NB1=$(zenity --entry --text "Combien de VM?")
-	if [ $? != 0 ]; then
-		echo "Interruption"; exit 1
-	fi
-
-	i=$NB1
-	((i++))
-	((i--))
-	if ! [ "$i" = "$NB1" ];
-	then
-		zenity --error --text "invalid value '$NB1'"
-		exit 1
-	fi
-	NB=$NB1
-	if [ $NB1 -lt 10 ]; then NB=0$NB1; fi
-	VMNAMES="${MOD}-01 à ${MOD}-${NB}"
+GROUPSEL=$(zenity --list --text "Quel groupe d'utilisateurs?" --column="Groupe" ${GROUPARR[@]} )
+if [ $? != 0 ]; then
+	echo "Interruption"; exit 1
 fi
+echo "GROUPSEL=$GROUPSEL"
+VMNAMES="${MOD}-XXX (avec XXX l'id user)"
+NB=$(wc -l <data_group_${GROUPSEL}.csv)
 
 MSGT="Ok pour créer $NB VM\n- sur le node $BASENODE,\n- nommées ${VMNAMES},\n- basées sur le template $TEMPLATE,\n- "
 if [ ${#TAGS} = 0 ]; then
@@ -203,86 +178,43 @@ if [ $? != 0 ]; then
 fi
 echo "START=$START"
 
+NUMA=1
+IFS=";";while read -a ARR
+do
+	IDU1=${ARR[0]}
+	IFS='@'; read -ra ARR2 <<< "$IDU1"; IFS=';'
+	IDU=${ARR2[0]}
+	NUMB=$NUMA
+	if [ 1 = ${#NUMA} ]; then NUMB="0$NUMA";fi
+	VMID=${YEARDAY}${ID}${NUMB}
+	VMNAME=${MOD}-${IDU}
+	echo "IDU1=$IDU1 IDU=$IDU VMID=$VMID VMNAME=$VMNAME"
+	((NUMA++))
+	CreateClone
 
-#-------------------------
-# Creation des clones
-if [ $NAMETYPE = NTN ];
-then
-	IFS=$'\n'
-	for i in $(seq 1 $NB)
-	do
-		NUM=$i
-		if [ 1 = ${#i} ]; then NUM="0$i";fi
-	#	echo "i=-$i- NUM=-$NUM-, size=${#NUM}"
-		VMID=${YEARDAY}${ID}${NUM}
-		VMNAME=${MOD}-${NUM}
-		
-		CreateClone
+	echo " -Ajout des tags"
+	AddTags
 
-		echo " -Ajout des tags"
-		AddTags
-
-		echo " -configuration permissions (roles)"
-		set -x
-	# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/access/acl	
-		response=$(curl -k \
-			-X PUT \
-			-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-			--data-urlencode "path=/vms/$VMID" \
-			--data-urlencode "groups=$GROUP" \
-			--data-urlencode "roles=PVEVMUser" \
-			"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/acl")
-		err=$?
-		set +x
-		echo "response=$response"
-		if ! [ $err = 0 ]; then
-			echo "response=-$response- err=$err"; exit 1
-		fi
-	done
-
-#			--data-urlencode "propagate=1" \
-
-# VM Naming holds userid
-else
-	NUMA=1
-	IFS=";";while read -a ARR
-	do
-		IDU1=${ARR[0]}
-		IFS='@'; read -ra ARR2 <<< "$IDU1"; IFS=';'
-		IDU=${ARR2[0]}
-		NUMB=$NUMA
-		if [ 1 = ${#NUMA} ]; then NUMB="0$NUMA";fi
-		VMID=${YEARDAY}${ID}${NUMB}
-		VMNAME=${MOD}-${IDU}
-		echo "IDU1=$IDU1 IDU=$IDU VMID=$VMID VMNAME=$VMNAME"
-		((NUMA++))
-		CreateClone
-
-		echo " -Ajout des tags"
-		AddTags
-
-		echo " -configuration permissions (roles)"
-	# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/access/acl	
-		response=$(curl --insecure --silent \
-			-X PUT \
-			-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-			--data-urlencode "path=/vms/$VMID" \
-			--data-urlencode "users=$IDU1" \
-			--data-urlencode "roles=PVEVMUser;PVEVMAdmin" \
-			"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/acl")
-		err=$?
-		echo "response=$response"
-		if ! [ $err = 0 ]; then
-			echo "response=-$response- err=$err"; exit 1
-		fi
-		if [ $response != '{\"data\":null}' ]; then
-			echo "Error: server said $response" 
-			exit 1
-		fi
-	done <data_group_${GROUPSEL}.csv
-fi
-
-#--data-urlencode "propagate=1" \
+	echo " -configuration permissions (roles)"
+# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/access/acl
+	response=$(curl --insecure --silent \
+		-X PUT \
+		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+		--data-urlencode "path=/vms/$VMID" \
+		--data-urlencode "users=$IDU1" \
+		--data-urlencode "roles=PVEVMUser;PVEVMAdmin" \
+		--data-urlencode "propagate=1" \
+		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/acl")
+	err=$?
+	echo "response=$response"
+	if ! [ $err = 0 ]; then
+		echo "response=-$response- err=$err"; exit 1
+	fi
+	if [ "$response" != "{\"data\":null}" ]; then
+		echo "Error: server said '$response'" 
+		exit 1
+	fi
+done <data_group_${GROUPSEL}.csv
 
 exit 0
 
