filenames cleanout

diff --git a/pgvm_list b/pgvm_list
--- a/pgvm_list
+++ b/pgvm_list
@@ -10,7 +10,7 @@ set +x
 # désactive l'interprétation de '!' dans une chaine
 set +H
 
-OUT=out_all.csv
+OUT=data_out_all.csv
 
 if [ -f $OUT ]; then rm $OUT; fi
 
@@ -46,25 +46,25 @@ function process()
 	sed -i -e 's/_/;/g' /tmp/proxmox/out_$1.csv
 
 # sort by name
-	sort --key=1 /tmp/proxmox/out_$1.csv >out_$1.csv
+	sort --key=1 /tmp/proxmox/out_$1.csv >data_out_$1.csv
 	
 # Add node name on each line, first position
 	IFS=";";while read line;
 	do
 		echo "$1;${line}" >> $OUT
- 	done < out_$1.csv
+ 	done < data_out_$1.csv
 
 	# extraction des template de chaque node
 	NBT=0
-	if [ -f template_$1.csv ]; then rm template_$1.csv; fi
+	rm template_$1.csv 2>/dev/null
 	IFS=";";while read -a ARR
 	do
 #		echo "0:${ARR[0]} - 1:${ARR[1]} - 2:${ARR[2]} - 3:${ARR[3]}"
 		if [ ${ARR[3]} = 1 ]
 		then
 			NBT=$((NBT+1))
-			echo "${ARR[1]};${ARR[2]};${ARR[0]}" >> template_$1.csv
-			echo "$1;${ARR[1]};${ARR[2]};${ARR[0]}" >> template_all.csv
+			echo "${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_$1.csv
+			echo "$1;${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_all.csv
 		fi
 
 # comptage du nb d'occurrence pour chaque tag
@@ -79,12 +79,11 @@ function process()
 				echo "$tag">>/tmp/proxmox/tags.csv
 			done
 		fi
-	done < out_$1.csv
+	done < data_out_$1.csv
 
-#	echo " -node '$1': $(wc -l <out_$1.csv) machines, dont $NBT template(s)"
-	NBTOT=$(wc -l <out_$1.csv)
+	NBTOT=$(wc -l <data_out_$1.csv)
 	((NBVM=NBTOT-NBT))
-	printf "| %10s | %5d | %9d | %5d |\n" $1 $NBVM $NBT $NBTOT
+	printf "| %10s | %3d | %7d | %5d |\n" $1 $NBVM $NBT $NBTOT
 	((TOT1+=NBVM))
 	((TOT2+=NBT))
 	((TOT3+=NBTOT))
@@ -93,21 +92,25 @@ function process()
 #---------------------------------------------------------------------------
 # Get list of nodes 
 clear
-echo "-Récupération liste des nodes..."
+#echo "-Récupération liste des nodes..."
 curl --silent -k \
 	-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-	https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes|jq | jq -r '.data[] | .node' >nodes.csv 2>>$CURLLOG
+	https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes|jq | jq -r '.data[] | .node' >data_nodes.csv 2>>$CURLLOG
+err=$?
+if ! [ $err = 0 ];
+then
+	echo "Error: API call failure, err=$?"
+	exit 1
+fi
 
-echo "-Nodes accessibles: $(wc -l < nodes.csv)"
-
-if [ -f /tmp/proxmox/tags.csv ]; then rm /tmp/proxmox/tags.csv; fi
-if [ -f template_all.csv ]; then rm template_all.csv; fi
+rm /tmp/proxmox/tags.csv 2>/dev/null
+rm data_template_* 2>/dev/null
 
 # associative array used to count tags
 declare -A TAGARR
 
-echo "|    Node    | Nb VM | Nb Templ. |  Tot  |"
-echo "|------------+-------+-----------+-------|"
+echo "|    Node    | #VM | #Templ. |  Tot  |"
+echo "|------------+-----+---------+-------|"
  
 TOT1=0
 TOT2=0
@@ -116,22 +119,22 @@ TOT3=0
 while read -r nodename
 do
 	process $nodename
-done < nodes.csv
+done < data_nodes.csv
 
-echo "|------------+-------+-----------+-------|"
-printf "      Totaux | %5d | %9d | %5d |\n" $TOT1 $TOT2 $TOT3
+echo "|------------+-----+---------+-------|"
+printf "      Totaux | %3d | %7d | %5d |\n" $TOT1 $TOT2 $TOT3
 
-echo -e "\n Available templates: $(wc -l<template_all.csv)"
+echo -e "\n Liste des $(wc -l<data_template_all.csv) templates:"
 printf "| %10s | %13s | %15s | %7s |\n" Node Name Tags VMid
 echo "|------------+---------------+-----------------+---------|"
 IFS=";";while read -a ARR
 do
 	printf "| %10s | %13s | %15s | %7s |\n" ${ARR[0]} ${ARR[1]} ${ARR[2]} ${ARR[3]}
-done < template_all.csv
+done < data_template_all.csv
 echo "|------------+---------------+-----------------+---------|"
 
 sort /tmp/proxmox/tags.csv >/tmp/proxmox/tags1.csv
-uniq /tmp/proxmox/tags1.csv >tags.csv
+uniq /tmp/proxmox/tags1.csv >data_tags.csv
 
 echo -e "\n|    Tags    | VM+T. |\n|------------+-------|"
 for i in "${!TAGARR[@]}"
@@ -160,7 +163,7 @@ fi
 jq -r '.userid + ";" + .groups + ";" + .email'</tmp/proxmox/users.json >/tmp/proxmox/users.csv
 
 sort /tmp/proxmox/users.csv >data_users.csv
-echo -e "\n-Nb utilisateurs enregistrés: $(wc -l<data_users.csv) "
+#echo -e "\n-Nb utilisateurs enregistrés: $(wc -l<data_users.csv) "
 
 # build one file per group
 rm data_group_*.csv 2>/dev/null
@@ -178,13 +181,7 @@ do
 done <data_users.csv
 
 sort /tmp/proxmox/groups1.csv >/tmp/proxmox/groups2.csv
-uniq /tmp/proxmox/groups2.csv > data_groups.csv
-
-# Parse file holding the users to get the one having no group
-
-
-NOGROUP=0
-
+uniq /tmp/proxmox/groups2.csv >data_groups.csv
 
 echo -e "\n|         Group           | #Users |\n|-------------------------+--------|"
 COMPT=0
