wip: user in VM names

diff --git a/pgvm_create b/pgvm_create
--- a/pgvm_create
+++ b/pgvm_create
@@ -64,27 +64,11 @@ IFS=";";while read -a ARR
 do
 	if [ ${ARR[0]} = $TEMPLATE ]
 	then
-		VMID=${ARR[2]}
+		TVMID=${ARR[2]}
 	fi 
 done < template_$NODE.csv
 
-echo "VMID=$VMID"
-
-
-NB=$(zenity --entry --text "Combien de VM?")
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
-
-#echo "NB=$NB"
-i=$NB
-((i++))
-((i--))
-if ! [ "$i" = "$NB" ];
-then
-	zenity --error --text "invalid value '$NB'"
-	exit 1
-fi
+echo "TVMID=$TVMID"
 
 
 MOD=$(zenity --entry --text "Donner le nom du module (RXXX, SAETTT)\n(servira pour le nom des VM)")
@@ -99,6 +83,36 @@ if [ $? != 0 ]; then
 	echo "Interruption"; exit 1
 fi
 echo "TAGS=$TAGS"
+
+
+NAMING=$(zenity --list --text "Type de nommage?" Numérotation Utilisateur )
+if [ $? != 0 ]; then
+	echo "Interruption"; exit 1
+fi
+echo "NAMING=$NAMING"
+
+if [ $NAMING = Utilisateur ]
+then
+	GROUPSEL=$(zenity --list --text "Quel groupe d'utilisateurs?" ${GROUPS[@]} )
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
+	fi
+	echo "GROUPSEL=$GROUPSEL"
+else
+	NB=$(zenity --entry --text "Combien de VM?")
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
+	fi
+
+	i=$NB
+	((i++))
+	((i--))
+	if ! [ "$i" = "$NB" ];
+	then
+		zenity --error --text "invalid value '$NB'"
+		exit 1
+	fi
+fi
 
 ID=$(zenity --entry --text "Donner l'identifiant commun à ce set de VM, entre 00 et 99\n(ne doit pas déja exister)")
 if [ $? != 0 ]; then
@@ -131,19 +145,20 @@ do
 	NUM=$i
 	if [ 1 = ${#i} ]; then NUM="0$i";fi
 #	echo "i=-$i- NUM=-$NUM-, size=${#NUM}"
-	echo "CREATION CLONE i=$NUM, nom=${MOD}-${NUM}, id=${YEARDAY}${ID}${NUM}"
-
+	VMID=${YEARDAY}${ID}${NUM}
+	echo "-Creation clone $i: nom=${MOD}-${NUM}, id=$VMID"
+	
 # ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/clone
 	response=$(curl -k \
 		--silent -X POST \
 		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-		"https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$NODE/qemu/$VMID/clone?node=$NODE&vmid=$VMID&newid=${YEARDAY}${ID}${NUM}&name=${MOD}-$i")
+		"https://${APINODE}.univ-rouen.fr:8006/api2/json/nodes/$NODE/qemu/$TVMID/clone?node=$NODE&vmid=$TVMID&newid=$VMID&name=${MOD}-$i")
 	err=$?
 	if ! [ $err = 0 ]; then
 		echo "response=-$response- err=$err"; exit 1
 	fi
 
-	echo "Ajout des tags"
+	echo " -Ajout des tags"
 # ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/config
 	response=$(curl -k \
 		--silent -X POST \
