ajout nb de VM On/Off

diff --git a/pgvm_create b/pgvm_create
--- a/pgvm_create
+++ b/pgvm_create
@@ -24,7 +24,7 @@ function CreateClone()
 	response=$(curl -k \
 		--silent -X POST \
 		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$TVMID/clone?node=$BASENODE&vmid=$TVMID&newid=$VMID&name=${VMNAME}" \
+		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$TVMID/clone" \
 		--data-urlencode node=$BASENODE \
 		--data-urlencode vmid=$TVMID \
 		--data-urlencode newid=$VMID \
@@ -37,19 +37,6 @@ function CreateClone()
 }
 
 #================================================================
-function AddTags()
-{
-# ref: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/config
-	response=$(curl -k \
-		--silent -X POST \
-		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
-		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$VMID/config?node=$BASENODE&vmid=$VMID&tags=$TAGS")
-	err=$?
-	if ! [ $err = 0 ]; then
-		echo "response=-$response- err=$err"; exit 1
-	fi
-}
-
 # re-create an array holding the nodes names
 unset NODEARR
 declare -a NODEARR
@@ -122,11 +109,22 @@ done
 
 echo "MOD=$MOD"
 
-TAGS=$(zenity --entry --text "Donner les tags a associer aux VMs, séparés par des virgules\n(pas d'espaces dans les tags!!)")
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
-echo "TAGS=$TAGS"
+
+DONE=NO
+while [ $DONE = NO ]
+do
+
+	TAGS=$(zenity --entry --text "Donner les tags a associer aux VMs, séparés par des virgules\n(pas d'espaces dans les tags!!)")
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
+	fi
+	echo "TAGS=$TAGS"
+	if [ ${#TAGS} = 0 ]; then
+		echo "Erreur, donner au moin un tag!"
+	else
+		DONE=YES
+	fi
+done
 
 DONE=NO
 while [ $DONE = NO ]
@@ -193,7 +191,19 @@ do
 	CreateClone
 
 	echo " -Ajout des tags"
-	AddTags
+	response=$(curl -k \
+		--silent -X POST \
+		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$BASENODE/qemu/$VMID/config?node=$BASENODE&vmid=$VMID&tags=$TAGS")
+	err=$?
+	if ! [ $err = 0 ]; then
+		echo "response=-$response- err=$err"; exit 1
+	fi
+	if [ "$response" != "{\"data\":null}" ]; then
+		echo "Error: server said '$response'" 
+		exit 1
+	fi
+
 
 	echo " -configuration permissions (roles)"
 # ref: https://pve.proxmox.com/pve-docs/api-viewer/#/access/acl
