wip: single file integration

diff --git a/pgvm b/pgvm
--- a/pgvm
+++ b/pgvm
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# tmp
+SINGLEFILE=Y
 
 # name: pgvm ("Proxmox Gestion VM")
 # S. Kramm, URN, 2026
@@ -31,48 +33,284 @@ export PORT
 
 
 #================================================================
+# Fetch data of a given node ($1), called by FetchData()
+function ProcessNode()
+{
+	if [ "$DEBUG" = "Y" ];then echo "process node $1"; fi
+	curl --insecure --silent -X GET \
+		-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+		https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes/$1/qemu?full=1 | jq -r '.data[]' >/tmp/proxmox/node_$1.json 2>>$CURLLOG
+	err=$?
+	if ! [ $err = 0 ]
+	then
+		echo "node '$1': echec!"
+		exit 1
+	fi
+# we use the '_' character to separate fields because in the json file, multiple tags are separated with ';'
+# (and '_' is not allowed in the VM name field)
+	jq -r '(.vmid|tostring) + "_" + .name + "_" + .tags + "_" + (.template|tostring) + "_" + .status' < /tmp/proxmox/node_$1.json >/tmp/proxmox/node_$1.csv
+
+# replace null by 0 (machine not a template), just to make it prettier
+	sed -i -e 's/_null/_0/g' /tmp/proxmox/node_$1.csv
+
+# replace the semi-colon separating tags with a comma
+	sed -i -e 's/;/,/g' /tmp/proxmox/node_$1.csv
+
+# replace the underscore by semi-colon
+	sed -i -e 's/_/;/g' /tmp/proxmox/node_$1.csv
+
+# sort by name
+	sort --key=1 /tmp/proxmox/node_$1.csv >data_node_$1.csv
+	
+# Add node name on each line, first position
+	IFS=";";while read line;
+	do
+		echo "$1;${line}" >> data_node_ALL.csv
+		
+ 	done < data_node_$1.csv
+
+	# extraction des template de chaque node
+
+#	NBT=0
+#	rm template_$1.csv 2>/dev/null
+	IFS=";";while read -a ARR
+	do
+#		echo "0:${ARR[0]} - 1:${ARR[1]} - 2:${ARR[2]} - 3:${ARR[3]}"
+#		if [ ${ARR[3]} = 1 ]
+#		then
+#			NBT=$((NBT+1))
+#			echo "${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_$1.csv
+#			echo "$1;${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_ALL.csv
+#		fi
+
+# comptage du nb d'occurrence pour chaque tag
+# TODO: supprimer quand on aura les csv par tag
+		if ! [ "${ARR[2]}" = "" ]
+		then
+			tags=${ARR[2]}
+			IFS=","; read -a ARR2 <<< "$tags"; IFS=";"
+			for ((i=0;i<${#ARR2[@]}; i++))
+			do
+				tag=${ARR2[$i]}
+				((TAGARR[$tag]++))
+				echo "$tag">>/tmp/proxmox/tags.csv
+			done
+		fi
+	done < data_node_$1.csv
+}
+
+
+#================================================================
+# Fetch all the data
+# This function does not print anything
+function FetchData()
+{
+	# Fetch list of nodes
+	curl --silent -k \
+		-H "Authorization: PVEAPIToken=$PVUSER@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+		https://${APINODE}.${DOMAIN}:${PORT}/api2/json/nodes|jq | jq -r '.data[] | .node' >data_nodes.csv 2>>$CURLLOG
+	err=$?
+	if ! [ $err = 0 ];
+	then
+		echo "Error: API call failure, err=$?"
+		exit 1
+	fi
+
+	rm /tmp/proxmox/tags.csv 2>/dev/null
+
+	# Associative array used to count tags
+	declare -A TAGARR
+
+# Main API loop, iterate on all nodes and collect all the nodes data
+	while read -r nodename
+	do
+		ProcessNode $nodename
+	done < data_nodes.csv
+
+	sort /tmp/proxmox/tags.csv >/tmp/proxmox/tags1.csv
+	uniq /tmp/proxmox/tags1.csv >data_tags.csv
+
+
+# Generate data file for templates
+	rm data_template_* 2>/dev/null
+	NBT=0
+	while read -r NODE
+	do
+		IFS=";"; while read -a ARR
+		do
+	#		echo "0:${ARR[0]} - 1:${ARR[1]} - 2:${ARR[2]} - 3:${ARR[3]}"
+			if [ ${ARR[3]} = 1 ]; then
+				((NBT++))
+				echo "${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_$NODE.csv
+				echo "$NODE;${ARR[1]};${ARR[2]};${ARR[0]}" >> data_template_ALL.csv
+			fi
+		done < data_node_$NODE.csv
+	done < data_nodes.csv
+
+# Generate a csv file for each group, holding the users
+	curl --insecure --silent -X GET \
+		-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+		"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/access/users?full=1" | jq '.data[]' >/tmp/proxmox/users.json
+
+	err=$?
+	if [ $err != 0 ]; then
+		echo "Error: failure of operation, err=$err";
+		exit 1
+	fi
+
+	# convert json into 3-fields CSV file
+	jq -r '.userid + ";" + .groups + ";" + .email'</tmp/proxmox/users.json >/tmp/proxmox/users.csv
+
+	sort /tmp/proxmox/users.csv >data_users.csv
+	#echo -e "\n-Nb utilisateurs enregistrés: $(wc -l<data_users.csv) "
+
+	# build one file per group
+	rm data_group_*.csv 2>/dev/null
+	declare -A NBUSGR
+	if [ -f /tmp/proxmox/groups1.csv ]; then rm /tmp/proxmox/groups1.csv; fi
+	IFS=";";while read -a TAB
+	do
+		GR=${TAB[1]}
+		echo "$GR">>/tmp/proxmox/groups1.csv
+		if ! [ "$GR" = "" ]; then
+			echo "${TAB[0]};${TAB[2]}" >> data_group_${GR}.csv
+		else
+			echo "${TAB[0]};${TAB[2]}" >> data_group_NOGROUP.csv
+		fi
+	done <data_users.csv
+
+	sort /tmp/proxmox/groups1.csv >/tmp/proxmox/groups2.csv
+	uniq /tmp/proxmox/groups2.csv >data_groups.csv
+}
+
+
+#================================================================
+function ShowNodes()
+{
+	echo "|    Node    | #VM | #Templ. |  Tot  |"
+	echo "|------------+-----+---------+-------|"
+
+	TOTVM=0
+	TOTT=0
+	TOTALL=0
+
+	while read -r NODE
+	do
+		NBTOT=$(wc -l <data_node_$NODE.csv)
+		NBT=$(wc -l <data_template_$NODE.csv)
+		
+		((NBVM=NBTOT-NBT))
+		printf "| %10s | %3d | %7d | %5d |\n" $NODE $NBVM $NBT $NBTOT
+		((TOTVM+=NBVM))
+		((TOTT+=NBT))
+		((TOTALL+=NBTOT))
+	done < data_nodes.csv
+
+	echo "|------------+-----+---------+-------|"
+	printf "      Totaux | %3d | %7d | %5d |\n" $TOTVM $TOTT $TOTALL
+}
+
+#================================================================
+function ShowTemplates()
+{
+	echo -e "\n-Liste des $(wc -l<data_template_ALL.csv) templates:"
+	printf "| %12s | %13s | %15s | %7s |\n" Node Name Tags VMid
+	echo "|--------------+---------------+-----------------+---------|"
+	IFS=";";while read -a ARR
+	do
+		printf "| %12s | %13s | %15s | %7s |\n" ${ARR[0]} ${ARR[1]} ${ARR[2]} ${ARR[3]}
+	done < data_template_ALL.csv
+	echo "|--------------+---------------+-----------------+---------|"
+}
+
+#================================================================
+function ShowTags()
+{
+	COMPT=0
+	printf "\n|   %2d Tags  | #VM+T. |\n|------------+--------|\n" $(wc -l <data_tags.csv)
+	NUM=1
+	for i in "${!TAGARR[@]}"
+	do
+		printf "| %10s | %6d |\n" $i ${TAGARR[$i]}
+		((COMPT+=${TAGARR[$i]}))
+		((NUM++))
+	done
+	echo "|------------+--------|"
+	printf "       Total | %6d |\n" $COMPT
+}
+
+#================================================================
+function ShowGroups()
+{
+	echo -e "\n-Nb d'utilisateurs: $(wc -l <data_users.csv), répartis dans $(wc -l <data_groups.csv) groupes"
+	echo -e "|         Group           | #Users |\n|-------------------------+--------|"
+	COMPT=0
+	IFS=";";while read groupname
+	do
+		if ! [ "$groupname" = "" ]; then
+			nb=$(wc -l <data_group_${groupname}.csv)
+			printf "| %23s | %6d |\n" $groupname $nb
+			((COMPT+=nb))
+		fi
+	done <data_groups.csv
+
+	NBNOGROUP=$(wc -l <data_group_NOGROUP.csv)
+	printf "|           (no group)    | %6d |\n" $NBNOGROUP
+	((COMPT+=NBNOGROUP))
+	echo "|-------------------------+--------|"
+	printf "                  Total   | %6d |\n" $COMPT
+}
+
+#================================================================
+function ShowDashboard()
+{
+	ShowNodes
+	ShowTemplates
+	ShowTags
+	ShowGroups
+}
+
+#================================================================
+# Delete a set of VM holding a given tag
 function DeleteVm()
 {
-if ! [ -f data_tags.csv ]
-then
-	echo "Erreur, fichier 'data_tags.csv' inaccessible"
-	exit 1
-fi
+	if ! [ -f data_tags.csv ]
+	then
+		echo "Erreur, fichier 'data_tags.csv' inaccessible"
+		exit 1
+	fi
 
-declare -a TAGARR
-IFS=";";while read TAG
-do
-	TAGARR+=($TAG)
-done <data_tags.csv
-#echo "TAGARR=${TAGARR[@]}"	
+	declare -a TAGARR
+	IFS=";";while read TAG
+	do
+		TAGARR+=($TAG)
+	done <data_tags.csv
+	#echo "TAGARR=${TAGARR[@]}"	
 
-TAGDEL=$(zenity --list --text="Quel machines ayant le tag ci-dessous souhaitez-vous détruire?" --column="tags" ${TAGARR[@]})
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
+	TAGDEL=$(zenity --list --text="Quel machines ayant le tag ci-dessous souhaitez-vous détruire?" --column="tags" ${TAGARR[@]})
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
+	fi
 
 # count VM only (not templates, as these will not be deleted)
 #echo "TAGDEL=$TAGDEL"
-COUNT=0
-IFS=";";while read -a ARR
-do
-	if [ ${ARR[3]} = 0 ]; then ((COUNT++)); fi
-done < data_tag_${TAGDEL}.csv
+	COUNT=0
+	IFS=";";while read -a ARR
+	do
+		if [ ${ARR[3]} = 0 ]; then ((COUNT++)); fi
+	done < data_tag_${TAGDEL}.csv
 
-START=$(zenity --question --text \
-	"Ok pour effacer les ${COUNT} VMs associées au tag $TAGDEL?")
+	zenity --question --text \
+		"Ok pour effacer les ${COUNT} VMs associées au tag $TAGDEL?"
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
+	fi
 
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
-#echo "START=$START"
-#exit 1
 
 #-------------------------
 # Delete VMs
 # TODO: pas plus simple de lire dans le fichier tags_XXXX.csv ???
 
-set +x
 COMPT=0
 IFS=";";while read -a TAB
 do
@@ -109,121 +347,121 @@ read
 
 
 #================================================================
+# Show list of VM holding a given tag
 function ViewTags()
 {
-# re-create an array holding the tag names
-declare -a TAGARR
-while read -r tagname
-do
-	TAGARR+=($tagname)
-done < data_tags.csv
+	# re-create an array holding the tag names
+	declare -a TAGARR
+	while read -r tagname
+	do
+		TAGARR+=($tagname)
+	done < data_tags.csv
 
-VTAG=$(zenity --list --height=300 --text="Quel tag?" --column="Tags" "${TAGARR[@]}")
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
-
-if [ "$DEBUG" = "N" ]; then clear; fi
-echo -e "\n-Liste des $(wc -l<data_tag_$VTAG.csv) machines ayant le tag '$VTAG':"
-printf "| VM/T |      Node     |       Nom       |    VMId     |      Tags       |\n";
-printf "|------+---------------+-----------------+-------------+-----------------|\n"
-
-IFS=";";while read -a TAB
-do
-	if [ ${TAB[3]} == 1 ]; then
-		printf "|  T   |"
-	else
-		printf "|  VM  |"
+	VTAG=$(zenity --list --height=300 --text="Quel tag?" --column="Tags" "${TAGARR[@]}")
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
 	fi
-	printf " %-13s | %-15s | %11d | %15s |\n" ${TAB[0]} ${TAB[2]} ${TAB[1]} ${TAB[4]} 
-done <data_tag_$VTAG.csv
-printf "|------+---------------+-----------------+-------------+-----------------|\n"
+
+	if [ "$DEBUG" = "N" ]; then clear; fi
+	echo -e "\n-Liste des $(wc -l<data_tag_$VTAG.csv) machines ayant le tag '$VTAG':"
+	printf "| VM/T |      Node     |       Nom       |    VMId     |      Tags       |\n";
+	printf "|------+---------------+-----------------+-------------+-----------------|\n"
+
+	IFS=";";while read -a TAB
+	do
+		if [ ${TAB[3]} == 1 ]; then
+			printf "|  T   |"
+		else
+			printf "|  VM  |"
+		fi
+		printf " %-13s | %-15s | %11d | %15s |\n" ${TAB[0]} ${TAB[2]} ${TAB[1]} ${TAB[4]} 
+	done <data_tag_$VTAG.csv
+	printf "|------+---------------+-----------------+-------------+-----------------|\n"
 }
 
 
 #================================================================
+# Show list of users in a given group
 function ViewGroups()
 {
 # create an array holding the group names, just for the zenity call below
-declare -a GROUPARR
-while read -r group
-do
-	GROUPARR+=($group)
-done < data_groups.csv
+	declare -a GROUPARR
+	while read -r group
+	do
+		GROUPARR+=($group)
+	done < data_groups.csv
 
-GROUPARR+=("(Sans groupe)")
+	GROUPARR+=("(Sans groupe)")
 
-GROUP=$(zenity --list --height=300 --text="Quel groupe?" --column="groupes" "${GROUPARR[@]}")
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
+	GROUP=$(zenity --list --height=300 --text="Quel groupe?" --column="groupes" "${GROUPARR[@]}")
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
+	fi
 
-#echo "GROUP=$GROUP"
-if [ "$GROUP" = "(Sans groupe)" ]; then
-	GROUPFILE=data_group_NOGROUP.csv
-else
-	GROUPFILE=data_group_$GROUP.csv
-fi
+	#echo "GROUP=$GROUP"
+	if [ "$GROUP" = "(Sans groupe)" ]; then
+		GROUPFILE=data_group_NOGROUP.csv
+	else
+		GROUPFILE=data_group_$GROUP.csv
+	fi
 
-if [ "$DEBUG" = "N" ]; then clear; fi
-GROUPSIZE=$(wc -l <$GROUPFILE)
-echo "-Groupe '$GROUP': $GROUPSIZE utilisateurs"
+	if [ "$DEBUG" = "N" ]; then clear; fi
+	GROUPSIZE=$(wc -l <$GROUPFILE)
+	echo "-Groupe '$GROUP': $GROUPSIZE utilisateurs"
 
-printf "|       Id       |                   email                  |\n";
-printf "|----------------+------------------------------------------|\n"
+	printf "|       Id       |                   email                  |\n";
+	printf "|----------------+------------------------------------------|\n"
 
-IFS=";";while read -a TAB
-do
-#	if [ "$GROUP" = "${TAB[1]}" ];
-#	then
+	IFS=";";while read -a TAB
+	do
 		printf "| %14s | %-40s |\n" ${TAB[0]} ${TAB[1]}
-#	fi
-done <$GROUPFILE
-printf "|----------------+------------------------------------------|\n"
+	done <$GROUPFILE
+	printf "|----------------+------------------------------------------|\n"
 }
 
 
 #================================================================
+# Show list of VM on a given node
 function ViewVM()
 {
 # re-create an array holding the nodes names
-declare -a NODEARR
-while read -r nodename
-do
-	NODEARR+=($nodename)
-done < data_nodes.csv
+	declare -a NODEARR
+	while read -r nodename
+	do
+		NODEARR+=($nodename)
+	done < data_nodes.csv
 
-VNODE=$(zenity --list --text="Quel node?" --column="node" "${NODEARR[@]}")
-if [ $? != 0 ]; then
-	echo "Interruption"; exit 1
-fi
-
-if ! [ "$DEBUG" = "N" ]; then clear; fi
-echo -e "\n-Liste des $(wc -l<data_node_$VNODE.csv) machines du node '$VNODE':"
-printf "| VM/T |    |        Nom       |    VMId    |     Tags      |\n";
-printf "|------+----+------------------+------------+---------------|\n"
-NBON=0
-IFS=";";while read -a TAB
-do
-	if [ ${TAB[3]} == 1 ]; then
-		printf "|  T   | - "
-	else
-		printf "|  VM  | "
-
-		if [ ${TAB[4]} = "stopped" ]; then
-			echo -n "🔴"
-		else
-			echo -n "🟢"
-			((NBON++))
-		fi
+	VNODE=$(zenity --list --text="Quel node?" --column="node" "${NODEARR[@]}")
+	if [ $? != 0 ]; then
+		echo "Interruption"; exit 1
 	fi
-	printf " | %-16s | %10d | %13s |\n" ${TAB[1]} ${TAB[0]} ${TAB[2]}
-done <data_node_$VNODE.csv
-printf "|------+----+------------------+------------+---------------|\n"
-NBT=$(wc -l <data_template_$VNODE.csv)
-NBTOT=$(wc -l <data_node_$VNODE.csv)
-((NBVM=NBTOT-NBT))
-echo "Bilan: $NBT templates et $NBVM VM, dont $NBON en fonctionnement"
+
+	if ! [ "$DEBUG" = "N" ]; then clear; fi
+	echo -e "\n-Liste des $(wc -l<data_node_$VNODE.csv) machines du node '$VNODE':"
+	printf "| VM/T |    |        Nom       |    VMId    |     Tags      |\n";
+	printf "|------+----+------------------+------------+---------------|\n"
+	NBON=0
+	IFS=";";while read -a TAB
+	do
+		if [ ${TAB[3]} == 1 ]; then
+			printf "|  T   | - "
+		else
+			printf "|  VM  | "
+
+			if [ ${TAB[4]} = "stopped" ]; then
+				echo -n "🔴"
+			else
+				echo -n "🟢"
+				((NBON++))
+			fi
+		fi
+		printf " | %-16s | %10d | %13s |\n" ${TAB[1]} ${TAB[0]} ${TAB[2]}
+	done <data_node_$VNODE.csv
+	printf "|------+----+------------------+------------+---------------|\n"
+	NBT=$(wc -l <data_template_$VNODE.csv)
+	NBTOT=$(wc -l <data_node_$VNODE.csv)
+	((NBVM=NBTOT-NBT))
+	echo "Bilan: $NBT templates et $NBVM VM, dont $NBON en fonctionnement"
 }
 
 #================================================================
@@ -239,10 +477,9 @@ function ToolCheck()
 function VarCheck()
 {
 	if [ "$1" = "" ]; then
-		echo "Error: variable '$1' is empty, please check manual and file '$TOKEN_FILE'"
+		echo "Error: variable '$2' is empty, please check manual and file '$TOKEN_FILE'"
 		exit 1
 	fi
-	
 }
 
 
@@ -256,13 +493,12 @@ ToolCheck jq
 ToolCheck zenity
 
 # Check that these variables are not empty
-VarCheck $TOK_VALUE
-VarCheck $TOK_NAME
-VarCheck $REALM
-VarCheck $CURLLOG
-VarCheck $APINODE
-VarCheck $DOMAIN
-VarCheck $PORT
+VarCheck $TOK_VALUE  TOK_VALUE
+VarCheck $TOK_NAME TOK_NAME
+VarCheck $REALM REALM
+VarCheck $APINODE APINODE
+VarCheck $DOMAIN DOMAIN
+VarCheck $PORT PORT
 
 TODAY=$(date '+%Y%m%d_%H%M%S')
 CURLLOG=/tmp/proxmox/curl_$TODAY.log
@@ -280,8 +516,12 @@ fi
 #echo "response=$response"
 echo "-connection API: fonctionnelle!"
 
-
-./pgvm_list
+if [ $SINGLEFILE = Y ]; then
+	FetchData
+	ShowDashboard
+else
+	./pgvm_list
+fi
 
 items=("Affichage inventaire" "Liste VMs par Node" "Création VMs" "Suppression VMs" "Liste des users par groupe" "Liste VM par tag")
 
@@ -294,6 +534,8 @@ do
 		echo "Interruption"; exit 1
 	fi
 
+if [ $SINGLEFILE = N ]; then
+
 	case "$item" in
 		"${items[0]}") ./pgvm_list;;
 		"${items[1]}") ViewVM;;
@@ -303,6 +545,17 @@ do
 		"${items[5]}") ViewTags;;
 		*) echo "Ooops! Invalid option.";;
 	esac
+else
+	case "$item" in
+		"${items[0]}") ShowDashboard;;
+		"${items[1]}") ViewVM;;
+		"${items[2]}") ./pgvm_create; FetchData; ShowDashboard;;
+		"${items[3]}") DeleteVm; FetchData; ShowDashboard;;
+		"${items[4]}") ViewGroups;;
+		"${items[5]}") ViewTags;;
+		*) echo "Ooops! Invalid option.";;
+	esac
+fi
 done
 
 if ! [ "$DEBUG" = "Y" ]; then rm /tmp/proxmox/* 2>/dev/null; fi
