api checl clarification

diff --git a/pgvm b/pgvm
--- a/pgvm
+++ b/pgvm
@@ -7,7 +7,8 @@ VERSION=20260630
 # https://pve.proxmox.com/pve-docs/api-viewer/
 
 
-# TODO: ajouter possibilité d'ajouter un groupe aux permissions
+# TODO ajouter commande de basculement d'un lot de VM depuis HDD vers SSD et inversement (via tag)
+# TODO ajouter possibilité d'ajouter un groupe aux permissions
 
 # TODO dashboard tag: ajouter colonnes indiquant nbe T et VM, et Nb ON/OFF
 # TODO bug (parfois): une fois des machines avec un tag créées, quand on les supprime, le tag reste à une valeur incorrecte
@@ -17,7 +18,7 @@ VERSION=20260630
 # un arbitraitement (genre initiales + YYMMDD ?)
 
 # TODO: ajouter option lors de la création de machines pour distribuer les VM sur les (3) noeuds
-# en pratique, elles sont toute créées sur le même node, il faut enuite faire une migration
+# en pratique, elles sont toute créées sur le même node, il faut ensuite faire une migration
 
 # TODO ajouter une visualisation des taches en cours (utilie dans le cas de migration en masse)
 # voir https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/tasks
@@ -44,13 +45,17 @@ then
 fi
 source $TOKEN_FILE
 
-# fix this in case your storage has different names
-CEPH_SSD_NAME=ceph-ssd
-CEPH_HDD_NAME=ceph-hdd
+if [ "$CEPH_SSD_NAME" = "" ]; then
+	CEPH_SSD_NAME=ceph-ssd
+fi
+if [ "$CEPH_HDD_NAME" = "" ]; then
+	CEPH_HDD_NAME=ceph-hdd
+fi
 
 #================================================================
 function ApiCall()
 {
+# TODO remove this, pointless
 	if [ "$DEBUG" = "Y" ]; then
 		if [ "$2" = "" ]
 		then
@@ -956,10 +961,26 @@ CURLLOG=/tmp/proxmox/curl_$TODAY.log
 # All temporary files are stored over there
 mkdir -p /tmp/proxmox
 
-# TODO: bug, en cas de non réponse, pas de message d'erreur !!
 # test de la réponse de l'API
+
 echo "-Test de la réponse de l'API"
-ApiCall GET "/api2/json/version"
+ping -c 1 ${APINODE}.${DOMAIN} 2>/dev/null
+if ! [ $? = 0 ]; then
+	echo "Error: DNS failure on ${APINODE}.${DOMAIN}"
+	exit 1
+fi
+
+curl --insecure \
+	--connect-timeout 5 \
+	--silent -X GET \
+	-H "Authorization: PVEAPIToken=${PVUSER}@${REALM}!${TOK_NAME}=${TOK_VALUE}" \
+	"https://${APINODE}.${DOMAIN}:${PORT}/api2/json/version"
+	if ! [ $? = 0 ];
+	then
+		echo "Error: API not reachable, please check credentials in file '$TOKEN_FILE'"
+		exit 1
+	fi
+
 echo "-connection API: fonctionnelle!"
 
 # Associative array used to count tags
@@ -989,6 +1010,7 @@ items=("Affichage Dashboard" \
 	"Start/Stop par tag" \
 	"Liste des users par groupe")
 
+# option -v: string gets stored in variable
 printf -v CEPH "Stockage ceph: hdd=%.2f%% ssd=%.2f%%" $CEPH_HDD $CEPH_SSD
 
 while item=$(zenity --height=400 --width=300 --list \
